language: php

services:
  - docker
php:
  - '5.6'
  - '7.0'
allow_failures:
  - php: 7.0
script: 
  -  docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix . --dry-run
notifications:
  email:
    - wdelenclos@gmail.com
  slack: esgi-iw:jMKTnfcE3dCoMIaUT3isyCbk

